### ISSUE TITLE
Cannot find `x86_64-unknown-hermit` target

### ISSUE THREAD

**Issue by phial3** [hermitcore/rust-std-hermit#7]
platform: MacOS M2

download release pkg and execute `install.sh` finished:
<img width="897" alt="image" src="https://github.com/user-attachments/assets/32f99e0b-039b-41c0-acd6-d354fce6fa99">

current rust default channel rustup stable:
```bash
stable-aarch64-apple-darwin (default)
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
```
<img width="547" alt="image" src="https://github.com/user-attachments/assets/97d0a881-2af3-412d-aedf-bef7c61ad723">

what should i do?

**Comment by mkroening** [comment]
The `rust-toolchain.toml` selects Rust `1.80.0`, not Rust `1.80.1`. https://github.com/hermit-os/hermit-rs-template/pull/71 should fix that.

Does that resolve your issue? :)

**Comment by phial3** [comment]
> The `rust-toolchain.toml` selects Rust `1.80.0`, not Rust `1.80.1`. [hermit-os/hermit-rs-template#71](https://github.com/hermit-os/hermit-rs-template/pull/71) should fix that.
> 
> Does that resolve your issue? :)

`hermit-rs-template/rust-toolchain.toml` already 1.80.0, what should i do:
<img width="533" alt="image" src="https://github.com/user-attachments/assets/98109397-d535-4201-8152-7b8c3140b939">

**Comment by mkroening** [comment]
Exactly. The [`rust-toolchain.toml` overrides the toolchain version](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) to `1.80.0`, but you installed rust-std-hermit for `1.80.1`. That's why I change `rust-toolchain.toml` to `1.80.1` in https://github.com/hermit-os/hermit-rs-template/pull/71.

**Comment by phial3** [comment]
> Exactly. The [`rust-toolchain.toml` overrides the toolchain version](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) to `1.80.0`, but you installed rust-std-hermit for `1.80.1`. That's why I change `rust-toolchain.toml` to `1.80.1` in [hermit-os/hermit-rs-template#71](https://github.com/hermit-os/hermit-rs-template/pull/71).

now rust channel is 1.80.0,
but still can't find it `x86_64-unknown-hermit`

**Comment by mkroening** [comment]
> now rust channel is 1.80.0

I know, but it has to be 1.80.1, not 1.80.0. Updating `hermit-rs-template` should work.

**Comment by mkroening** [comment]
Please reopen if this issue is not resolved. :)
